name: Deploy Umara CMS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Fix Permissions Before Pull
        run: |
          sudo chown -R devcom:www-data /var/www/cms-compro-umara/storage/
          sudo chown -R devcom:www-data /var/www/cms-compro-umara/bootstrap/cache/
          sudo chown -R devcom:www-data /var/www/cms-compro-umara/public/build/
          sudo chmod -R 775 /var/www/cms-compro-umara/storage/
          sudo chmod -R 775 /var/www/cms-compro-umara/bootstrap/cache/
          sudo chmod -R 775 /var/www/cms-compro-umara/public/build/

      - name: Pull Latest Code
        run: |
          cd /var/www/cms-compro-umara
          git fetch origin main
          git reset --hard origin/main

      - name: Install & Build Frontend
        run: |
          cd /var/www/cms-compro-umara
          npm ci
          npm run build
          rm -f public/hot

      - name: Install PHP Dependencies
        run: |
          cd /var/www/cms-compro-umara
          composer install --no-dev --optimize-autoloader

      - name: Deploy Laravel
        run: |
          cd /var/www/cms-compro-umara
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan storage:link

      - name: Fix Permissions After Deploy
        run: |
          sudo chown -R devcom:www-data /var/www/cms-compro-umara/storage/
          sudo chown -R devcom:www-data /var/www/cms-compro-umara/bootstrap/cache/
          sudo chown -R devcom:www-data /var/www/cms-compro-umara/public/build/
          sudo chmod -R 775 /var/www/cms-compro-umara/storage/
          sudo chmod -R 775 /var/www/cms-compro-umara/bootstrap/cache/
          sudo chmod -R 775 /var/www/cms-compro-umara/public/build/