name: Deploy Umara CMS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Latest Code
        run: |
          cd /var/www/cms-compro-umara
          git fetch origin main
          git reset --hard origin/main

      - name: Install & Build Frontend
        run: |
          cd /var/www/cms-compro-umara
          npm ci
          npm run build
          rm -f public/hot  # ← Tambah ini!

      - name: Install PHP Dependencies
        run: |
          cd /var/www/cms-compro-umara
          composer install --no-dev --optimize-autoloader

      - name: Deploy Laravel
        run: |
          cd /var/www/cms-compro-umara
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan storage:link