name: Deploy Umara CMS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install & Build Frontend
        run: |
          npm ci
          npm run build

      - name: Install PHP Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Deploy Laravel
        run: |
          cp -r public/build /var/www/cms-compro-umara/public/
          cd /var/www/cms-compro-umara
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan storage:link